### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by T1mey** [gregorwolf/pg-beershop#166]
Hi, 

I'm working on an app which should use a pg db. I'm follwing the tutorials but have some questions:

How does cds-pg is looking up the credentials on BTP?  I have boud my database to the application. So I can see the credentials.
I do not want to put them in package.json ... but without that I get an error 

error: no pg_hba.conf entry for host "x.x.x.x", user "XXX", database "XXX", SSL off

Any idea how to force looking them up ?

**Comment by gregorwolf** [comment]
Duplicate https://github.com/sapmentors/cds-pg/issues/232
