### ISSUE TITLE
Error: connect ECONNREFUSED 127.0.0.1:5432  while running the service

### ISSUE THREAD

**Issue by ranjith13119** [gregorwolf/pg-beershop#225]
Hello Gregorwolf, 

I can successfully deploy the project. But When I try to run the service URL it is giving the connect ECONNREFUSED 127.0.0.1:5432 error. Please find the attached error logs of the service module, mta.yaml and package.json files.

![image](https://user-images.githubusercontent.com/30929584/158029893-6b4b5e16-7e8e-4f7e-8ac1-89c605bba52e.png)

[devtoberfest-srv-2022-03-12 18_14_43.576+0000.txt](https://github.com/gregorwolf/pg-beershop/files/8238142/devtoberfest-srv-2022-03-12.18_14_43.576%2B0000.txt)
[mta.yaml.txt](https://github.com/gregorwolf/pg-beershop/files/8238151/mta.yaml.txt)
[package.txt](https://github.com/gregorwolf/pg-beershop/files/8238154/package.txt)

**Comment by gregorwolf** [comment]
Hi @ranjith13119 ,

please check the latest version. I think the issue is fixed there. For more details check my comment https://github.com/mikezaschka/cds-dbm/issues/87#issuecomment-1073129948.

CU
Gregor

**Comment by ranjith13119** [comment]
Hello @gregorwolf,

Now, thanks for the suggestion. Now I'm stuck with a new error https://github.com/gregorwolf/pg-beershop/issues/237

Could you please help me to resolve it.
