### ISSUE TITLE
Error: Cannot find module 'cds-dbm/dist/build/postgres-cf'

### ISSUE THREAD

**Issue by TNFlexso** [gregorwolf/pg-beershop#232]
Hi Gregor

I'm trying to build the MTAR but i get the following error:

[2022-03-24 09:30:28]  INFO executing the "cds build --production" command...
[cds] - determining build tasks for project [C:\Users\nelisth\Documents\projects\pg-beershop].
[cds] - the following build tasks will be executed
[cds] -    {
     "build": {
       "target": "gen",
       "tasks": [
         {"for":"node-cf", "src":"srv", "options":{"model":["db","srv","app"]}},
         {"for":"postgres-cf", "src":"db", "options":{"deployCmd":"npx cds-dbm deploy --load-via delta --auto-undeploy","model":["db","srv","app"]}}
       ]
     }
   }

[cds] - building project [C:\Users\nelisth\Documents\projects\pg-beershop], clean [true]
[cds] - cds [5.8.4], compiler [2.12.0], home [C:\Users\nelisth\Documents\projects\pg-beershop\node_modules\@sap\cds]

[cds] - Provider failed to load handler class - provider: DefaultBuildTaskProvider, task: postgres-cf :
Error: Build task could not be resolved - module [cds-dbm/dist/build/postgres-cf] cannot be loaded:
Error: Cannot find module 'cds-dbm/dist/build/postgres-cf'
Require stack:
- C:\Users\nelisth\Documents\projects\pg-beershop\node_modules\@sap\cds\bin\build\buildTaskEngine.js
- C:\Users\nelisth\Documents\projects\pg-beershop\node_modules\@sap\cds\bin\build\index.js
- C:\Users\nelisth\Documents\projects\pg-beershop\node_modules\@sap\cds\bin\cds.js
[cds] - [ERROR] Build task could not be resolved - module [cds-dbm/dist/build/postgres-cf] cannot be loaded:
Error: Cannot find module 'cds-dbm/dist/build/postgres-cf'
Require stack:
- C:\Users\nelisth\Documents\projects\pg-beershop\node_modules\@sap\cds\bin\build\buildTaskEngine.js
- C:\Users\nelisth\Documents\projects\pg-beershop\node_modules\@sap\cds\bin\build\index.js
- C:\Users\nelisth\Documents\projects\pg-beershop\node_modules\@sap\cds\bin\cds.js
[ERROR] Build task could not be resolved - module [cds-dbm/dist/build/postgres-cf] cannot be loaded:
Error: Cannot find module 'cds-dbm/dist/build/postgres-cf'
Require stack:
- C:\Users\nelisth\Documents\projects\pg-beershop\node_modules\@sap\cds\bin\build\buildTaskEngine.js
- C:\Users\nelisth\Documents\projects\pg-beershop\node_modules\@sap\cds\bin\build\index.js
- C:\Users\nelisth\Documents\projects\pg-beershop\node_modules\@sap\cds\bin\cds.js

[2022-03-24 09:30:29] ERROR the "before-all"" build failed: could not execute the "cds build --production" command: exit status 1
make: *** [Makefile_20220324092949.mta:28: pre_build] Error 1
Error: could not build the MTA project: could not execute the "make -f Makefile_20220324092949.mta p=cf mtar= strict=true mode=" command: exit status 2
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! pg-beershop@1.0.0 build:cf: `mbt build`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the pg-beershop@1.0.0 build:cf script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\nelisth\AppData\Roaming\npm-cache\_logs\2022-03-24T08_30_29_273Z-debug.log

**Comment by gregorwolf** [comment]
Have you tried a build using the SAP Business Applicaiton Studio? There you have a Linux environment. It works fine for me on my Mac.

**Comment by gregorwolf** [comment]
No reply. Closing.

**Comment by aytexss** [comment]
Hi Gregor,

i am running into the same issue. I tried it with a local installation on a Windows 10 system and cross checked with the Business Application Studio. The result in both cases are that the postgres-cf module is missing. I ran "npm ci" and "npm install cds-dbm" with no success. Am i missing a step?

**VS Code on MS Windows 10 System:**
PS C:\Temp\postgretest\pg-beershop> npm run build:cf

> pg-beershop@1.0.0 build:cf
> mbt build

[2022-11-30 10:16:52]  INFO Cloud MTA Build Tool version 1.2.20
[2022-11-30 10:16:52]  INFO generating the "Makefile_20221130101652.mta" file...
[2022-11-30 10:16:52]  INFO done
[2022-11-30 10:16:52]  INFO executing the "make -f Makefile_20221130101652.mta p=cf mtar= strict=true mode=" command...
[2022-11-30 10:16:53]  INFO validating the MTA project
[2022-11-30 10:16:53]  INFO running the "before-all" build...
[2022-11-30 10:16:53]  INFO executing the "npm install --production" command...
.npm WARN config production Use `--omit=dev` instead.
.npm WARN EBADENGINE Unsupported engine {
npm WARN EBADENGINE   package: 'pg-beershop@1.0.0',
npm WARN EBADENGINE   required: { node: '^14' },
npm WARN EBADENGINE   current: { node: 'v19.1.0', npm: '8.19.3' }
npm WARN EBADENGINE }
npm WARN EBADENGINE Unsupported engine {
npm WARN EBADENGINE   package: '@sap-ux/fe-fpm-writer@0.17.2',
npm WARN EBADENGINE   required: {
npm WARN EBADENGINE     node: '>= 14.16.0 < 15.0.0 || >=16.1.0 < 17.0.0 || >=18.0.0 < 19.0.0',
npm WARN EBADENGINE     pnpm: '>=6.26.1 < 7.0.0 || >=7.1.0'
npm WARN EBADENGINE   },
npm WARN EBADENGINE   current: { node: 'v19.1.0', npm: '8.19.3' }
npm WARN EBADENGINE }
npm WARN EBADENGINE Unsupported engine {
npm WARN EBADENGINE   package: '@sap-ux/vocabularies-types@0.5.7',
npm WARN EBADENGINE   required: {
npm WARN EBADENGINE     node: '>=12.22.5 < 13.0.0 || >= 14.16.0 < 15.0.0 || >=16.1.0 < 17.0.0',
npm WARN EBADENGINE     pnpm: '>=6.26.1'
npm WARN EBADENGINE   },
npm WARN EBADENGINE   current: { node: 'v19.1.0', npm: '8.19.3' }
npm WARN EBADENGINE }
npm WARN EBADENGINE Unsupported engine {
npm WARN EBADENGINE   package: '@sap/audit-logging@5.5.5',
npm WARN EBADENGINE   required: { node: '^10.0.0 || ^12.0.0 || ^14.0.0 || ^16.0.0' },
npm WARN EBADENGINE   current: { node: 'v19.1.0', npm: '8.19.3' }
npm WARN EBADENGINE }
npm WARN EBADENGINE Unsupported engine {
npm WARN EBADENGINE   package: '@sap/ux-specification@1.102.9',
npm WARN EBADENGINE   required: {
npm WARN EBADENGINE     node: '>= 14.16.0 < 15.0.0 || >= 16.1.0 < 17.0.0 || >= 18.0.0 < 19.0.0',
npm WARN EBADENGINE     yarn: '>=1.22.19 < 2'
npm WARN EBADENGINE   },
npm WARN EBADENGINE   current: { node: 'v19.1.0', npm: '8.19.3' }
npm WARN EBADENGINE }
npm WARN EBADENGINE Unsupported engine {
npm WARN EBADENGINE   package: '@sap/xsenv@3.3.2',
npm WARN EBADENGINE   required: { node: '^10.0.0 || ^12.0.0 || ^14.0.0 || ^16.0.0' },
npm WARN EBADENGINE   current: { node: 'v19.1.0', npm: '8.19.3' }
npm WARN EBADENGINE }
npm WARN EBADENGINE Unsupported engine {
npm WARN EBADENGINE   package: 'opossum@6.3.0',
npm WARN EBADENGINE   required: { node: '^16 || ^14 || ^12' },
npm WARN EBADENGINE   current: { node: 'v19.1.0', npm: '8.19.3' }
npm WARN EBADENGINE }
.....
up to date, audited 660 packages in 6s

89 packages are looking for funding
  run `npm fund` for details

4 vulnerabilities (2 moderate, 2 high)

To address issues that do not require attention, run:
  npm audit fix

To address all issues (including breaking changes), run:
  npm audit fix --force

Run `npm audit` for details.
[2022-11-30 10:17:00]  INFO executing the "cds build --production" command...
[cds] - determining build tasks for project [C:\Temp\postgretest\pg-beershop].
[cds] - the following build tasks will be executed
[cds] -    {
     "build": {
       "target": "gen",
       "tasks": [
         {"for":"node-cf", "src":"srv", "options":{"model":["db","srv","app"]}},
         {"for":"postgres-cf", "src":"db", "options":{"deployCmd":"npx cds-dbm deploy --load-via delta --auto-undeploy","model":["db","srv","app"]}}
       ]
     }
   }

[cds] - building project [C:\Temp\postgretest\pg-beershop], clean [true]
[cds] - cds [5.9.7], compiler [2.15.4], home [C:\Temp\postgretest\pg-beershop\node_modules\@sap\cds]

[cds] - Provider failed to load handler class - provider: DefaultBuildTaskProvider, task: postgres-cf :
Error: Build task could not be resolved - module [cds-dbm/dist/build/postgres-cf] cannot be loaded:
Error: Cannot find module 'cds-dbm/dist/build/postgres-cf'
Require stack:
- C:\Temp\postgretest\pg-beershop\node_modules\@sap\cds\bin\build\buildTaskProviderFactory.js
- C:\Temp\postgretest\pg-beershop\node_modules\@sap\cds\bin\build\buildTaskEngine.js
- C:\Temp\postgretest\pg-beershop\node_modules\@sap\cds\bin\build\index.js
- C:\Temp\postgretest\pg-beershop\node_modules\@sap\cds\bin\cds.js
[cds] - [ERROR] Build task could not be resolved - module [cds-dbm/dist/build/postgres-cf] cannot be loaded:
Error: Cannot find module 'cds-dbm/dist/build/postgres-cf'
Require stack:
- C:\Temp\postgretest\pg-beershop\node_modules\@sap\cds\bin\build\buildTaskProviderFactory.js
- C:\Temp\postgretest\pg-beershop\node_modules\@sap\cds\bin\build\buildTaskEngine.js
- C:\Temp\postgretest\pg-beershop\node_modules\@sap\cds\bin\build\index.js
- C:\Temp\postgretest\pg-beershop\node_modules\@sap\cds\bin\cds.js
[ERROR] Build task could not be resolved - module [cds-dbm/dist/build/postgres-cf] cannot be loaded:
Error: Cannot find module 'cds-dbm/dist/build/postgres-cf'
Require stack:
- C:\Temp\postgretest\pg-beershop\node_modules\@sap\cds\bin\build\buildTaskProviderFactory.js
- C:\Temp\postgretest\pg-beershop\node_modules\@sap\cds\bin\build\buildTaskEngine.js
- C:\Temp\postgretest\pg-beershop\node_modules\@sap\cds\bin\build\index.js
- C:\Temp\postgretest\pg-beershop\node_modules\@sap\cds\bin\cds.js

[2022-11-30 10:17:01] ERROR the "before-all"" build failed: could not execute the "cds build --production" command: exit status 1
make: *** [Makefile_20221130101652.mta:28: pre_build] Error 1
Error: could not build the MTA project: could not execute the "make -f Makefile_20221130101652.mta p=cf mtar= strict=true mode=" command: exit status 2

**SAP BTP Business Application Studio:**
user: pg-beershop $ npm run build:cf

> pg-beershop@1.0.0 build:cf
> mbt build

[2022-11-30 09:24:10]  INFO Cloud MTA Build Tool version 1.2.18
[2022-11-30 09:24:10]  INFO generating the "Makefile_20221130092410.mta" file...
[2022-11-30 09:24:10]  INFO done
[2022-11-30 09:24:10]  INFO executing the "make -f Makefile_20221130092410.mta p=cf mtar= strict=true mode=" command...
[2022-11-30 09:24:10]  INFO validating the MTA project
[2022-11-30 09:24:10]  INFO running the "before-all" build...
[2022-11-30 09:24:10]  INFO executing the "npm install --production" command...
npm WARN config production Use `--omit=dev` instead.
npm WARN EBADENGINE Unsupported engine {
npm WARN EBADENGINE   package: 'pg-beershop@1.0.0',
npm WARN EBADENGINE   required: { node: '^14' },
npm WARN EBADENGINE   current: { node: 'v16.16.0', npm: '8.11.0' }
npm WARN EBADENGINE }
..
changed 42 packages in 3s

55 packages are looking for funding
  run `npm fund` for details
[2022-11-30 09:24:13]  INFO executing the "cds build --production" command...
[cds] - determining build tasks for project [/home/user/projects/pg-beershop].
[cds] - the following build tasks will be executed
[cds] -    {
     "build": {
       "target": "gen",
       "tasks": [
         {"for":"node-cf", "src":"srv", "options":{"model":["db","srv","app"]}},
         {"for":"postgres-cf", "src":"db", "options":{"deployCmd":"npx cds-dbm deploy --load-via delta --auto-undeploy","model":["db","srv","app"]}}
       ]
     }
   }

[cds] - Provider failed to load handler class - provider: DefaultBuildTaskProvider, task: postgres-cf :
Error: Build task could not be resolved - module [cds-dbm/dist/build/postgres-cf] cannot be loaded:
Error: Cannot find module 'cds-dbm/dist/build/postgres-cf'
Require stack:
- /home/user/projects/pg-beershop/node_modules/@sap/cds/bin/build/buildTaskProviderFactory.js
- /home/user/projects/pg-beershop/node_modules/@sap/cds/bin/build/buildTaskEngine.js
- /home/user/projects/pg-beershop/node_modules/@sap/cds/bin/build/index.js
- /home/user/projects/pg-beershop/node_modules/@sap/cds/lib/index.js
- /home/user/projects/pg-beershop/node_modules/@sap/cds/bin/cds.js
- /extbin/npm/globals/lib/node_modules/@sap/cds-dk/bin/cds.js
[cds] - 
[ERROR] Build task could not be resolved - module [cds-dbm/dist/build/postgres-cf] cannot be loaded:
Error: Cannot find module 'cds-dbm/dist/build/postgres-cf'
Require stack:
- /home/user/projects/pg-beershop/node_modules/@sap/cds/bin/build/buildTaskProviderFactory.js
- /home/user/projects/pg-beershop/node_modules/@sap/cds/bin/build/buildTaskEngine.js
- /home/user/projects/pg-beershop/node_modules/@sap/cds/bin/build/index.js
- /home/user/projects/pg-beershop/node_modules/@sap/cds/lib/index.js
- /home/user/projects/pg-beershop/node_modules/@sap/cds/bin/cds.js
- /extbin/npm/globals/lib/node_modules/@sap/cds-dk/bin/cds.js

[2022-11-30 09:24:13] ERROR the "before-all"" build failed: could not execute the "cds build --production" command: exit status 1
make: *** [Makefile_20221130092410.mta:28: pre_build] Error 1
Error: could not build the MTA project: could not execute the "make -f Makefile_20221130092410.mta p=cf mtar= strict=true mode=" command: exit status 2
