### ISSUE TITLE
Relationship does not exist while trying to execute the "GET" operation

### ISSUE THREAD

**Issue by ranjith13119** [gregorwolf/pg-beershop#237]
Hello @gregorwolf,

Code Repository: [https://github.com/ranjith13119/CAP---Postgres.git]

As you suggested in my previous question I have used the latest version of the library.

But when I try to run the GET operation for any entity set it is giving the below error, 

![image](https://user-images.githubusercontent.com/30929584/161302645-e3e4d15c-dda2-4285-b43e-5b7cfc633734.png)

Could you help me to resolve this issue? I have attached the GITHUB URL to this post.

([https://github.com/ranjith13119/CAP---Postgres.git])

**Comment by gregorwolf** [comment]
Hi @ranjith13119,

if this would be an issue with my project pg-beershop I would try to help here. But your project at https://github.com/ranjith13119/CAP---Postgres seems to be based on https://github.com/mikezaschka/cap-devtoberfest from @mikezaschka. If it is an issue with cds-pg then please fork https://github.com/sapmentors/cds-pg, create a branch with a testcase and link that in an issue for the cds-pg project.

CU
Gregor
