### ISSUE TITLE
Error staging application: InsufficientResources - Insufficient resources

### ISSUE THREAD

**Issue by sparihar11** [gregorwolf/pg-beershop#244]
Hi @gregorwolf 

I get below error everytime I try to deploy application on business application studio. I have also tried to increase the memory space but still no luck. Could you please help here? 

Error staging application "devtoberfest-db-deployer": InsufficientResources - Insufficient resources
Error staging application "devtoberfest-srv": InsufficientResources - Insufficient resources

Thanks Shilpa

**Comment by gregorwolf** [comment]
Hi @sparihar11,

seems to be an issue in the SAP BTP Infrastructure. Check out [BTP Cloud Foundry trial - InsufficientResources - Insufficient resources](https://answers.sap.com/questions/13623220/btp-cloud-foundry-trial-insufficientresources-insu.html)

**Comment by sparihar11** [comment]
Thanks @gregorwolf  

Am quite surprised but
![build issue](https://user-images.githubusercontent.com/45871662/166154706-8aa55c80-0ef5-4c47-8138-cb160b5ac552.jpg)
 this issue got automatically resolved. I was able to build and deploy my project on BTP trial.

Although I tried implementing with the same technique on my company's DEV BTP environment and it fails at the initial build itself.  I am getting below error. Attaching the screenshot too. Could you please
![build issue](https://user-images.githubusercontent.com/45871662/166154721-7e2e0b7b-d960-4c0d-9f22-b65b3f011250.jpg)
 guide here?

External build task implementations are only allowed for npm scope @sap - package name [node-cf]

Thanks,
Shilpa

**Comment by gregorwolf** [comment]
Hi Shilpa,

I've cloned this repository to BAS and was able to build and deploy without issues. Can you confirm that pg-beershop also works for you? If you still have issues with your project the CAP community can help when you provide a sample project in a public Git repository.

CU
Gregor

**Comment by sparihar11** [comment]
@gregorwolf 

Please find project in below public git repository. Let me know if you were able to build this. I could not share the entire project so just shared the skeleton.

https://github.com/sparihar11/logs.git

Thanks,
Shilpa

**Comment by gregorwolf** [comment]
Hi @sparihar11,

the build works as soon as you would adjust the build task in the package.json according to my pg-beershop [package.json#L132](https://github.com/gregorwolf/pg-beershop/blob/main/package.json#L132). Also you should bring all your dependencies to the latest version. And use "node": "^14" instead of the not anymore supported node 10.

CU
Gregor

**Comment by sparihar11** [comment]
@gregorwolf Thanks a ton!! Your advice helped me resolve the build issue.

**Comment by jojimotive** [comment]
I have created one SAP CAP project which uses Postgresql hyper scalar as database. While deploying this the following error is coming.

#2.0#2023 03 29 04:45:48.136#Z#DEBUG#com.sap.cloud.lm.sl.xs2.5b928c0a-cdec-11ed-aef0-eeee0a8f79d8.devtoberfest-db-deployer.stageAppTask#######org.cloudfoundry.multiapps.controller.persistence.services.ProcessLogger########flowable-async-job-executor-thread-3037###[PollStageAppStatusExecution] [devtoberfest-db-deployer] 4785dd26-8d6d-4bea-b93b-e9624bcd57a1 [Wed Mar 29 04:45:44 UTC 2023] **ERROR** Unsupported stack (STDOUT, STG)#
[packagejson.txt](https://github.com/gregorwolf/pg-beershop/files/11103762/packagejson.txt)
[mtayaml.txt](https://github.com/gregorwolf/pg-beershop/files/11103763/mtayaml.txt)
