### ISSUE TITLE
No data when following local readme steps

### ISSUE THREAD

**Issue by sedacrivity** [gregorwolf/pg-beershop#245]
Hi Gregor,

Great example project.

Just a small remark - if one follows the steps in the readme for local deployment and you start cds run and open the url then there is no content ...

It seems the step `npx cds-dbm load --via delta` is nowhere mentioned.

**Comment by gregorwolf** [comment]
Would be great if you pack the improvements into a PR.

**Comment by sedacrivity** [comment]
Done. #248
