### ISSUE TITLE
TypeError: Cannot read properties of undefined (reading 'username')

### ISSUE THREAD

**Issue by sparihar11** [gregorwolf/pg-beershop#268]
@gregorwolf 

Did you face below error on deploying the app? I have also updated the npm to 8.9.0 still facing typeerror issue. I also do not have any property called username in my schema.
![image](https://user-images.githubusercontent.com/45871662/167606909-fb9304d7-bf0a-4f5b-a7f3-9c1b704617dc.png)

Thanks,
Shilpa

**Comment by sparihar11** [comment]
@gregorwolf 
I have supplied the data as well but still it's not working. Could you please advice here?

Thanks,
Shilpa

**Comment by gregorwolf** [comment]
Please check the differences of your project vs. my pg-beershop.

**Comment by sparihar11** [comment]
@gregorwolf 

Thank you so much for all help and support.
I was able to resolve issue after comparing and changing code as per your project.

Closing the issue.

Thanks,
Shilpa
