### ISSUE TITLE
Failed to deploy db-deployer module

### ISSUE THREAD

**Issue by Sandeep-Malhotra** [gregorwolf/pg-beershop#3]
Hello Gregor Wolf,
Thanks for such a detail repository. I tried to deploy the app and got below mentioned error
![image](https://user-images.githubusercontent.com/11954798/99355759-fad40280-28fc-11eb-9e4d-e3eec2718b96.png)
I  have subscribed the PostgreSQL in cloud and changed the mta.yaml accordingly ( screenshot attached)
![image](https://user-images.githubusercontent.com/11954798/99355887-34a50900-28fd-11eb-9964-c7a05eed2c74.png)

Kindly let me know what else I need to do 
Thanks 
Sandeep

**Comment by gregorwolf** [comment]
Hi Sandeep,

maybe there are two issues:

- When you're tring this on SAP CP Trial with the PostgreSQL Hyperscaler Option you have to wait until this issue: [Can't connect to PostgreSQL on SAP CP Trial, Hyperscaler Option](https://answers.sap.com/questions/13182819/cant-connect-to-postgresql-on-sap-cp-trial-hypersc.html) is fixed.
- The deploy is currently under heavy work in progress. Give it a try by enabling ssh to the module as [described here](https://github.com/gregorwolf/pg-beershop/tree/master/db-deployer) and run the script interactively.

Best regards
Gregor

**Comment by Sandeep-Malhotra** [comment]
Thanks Gregor. Am not using Trial version . I am using production version. and it is AWS

**Comment by Sandeep-Malhotra** [comment]
I just tried and able to reach the directory in cf but got permission denied to run deploy.sh

**Comment by gregorwolf** [comment]
Have you checked with ls -l what the actual permissions are? Also I would suggest that you enable the adminer module and try if you can reach the database there.

**Comment by Sandeep-Malhotra** [comment]
Thanks for your assistance. Am able to run deployer.sh file but got below mentioned error
![image](https://user-images.githubusercontent.com/11954798/99363483-e8f85c80-2908-11eb-8356-13eb6a4bd76d.png)

**Comment by Sandeep-Malhotra** [comment]
Also I got another issue 
![image](https://user-images.githubusercontent.com/11954798/99377764-b6eff600-291a-11eb-9eb6-6f754c7d4844.png)

**Comment by gregorwolf** [comment]
Please check out the new [db-deployer-java](https://github.com/gregorwolf/pg-beershop/tree/master/db-deployer-java). Here I directly use the latest version of cds-pg and cds-dbm which include the latest fixes. Also it uses a combination of the Node.JS and Java buildpack. That way I don't need to download Java manually anymore.

**Comment by Sandeep-Malhotra** [comment]
Sure Will check. I tried with new project and this time My service is unable to connect to PostgreSQL

![image](https://user-images.githubusercontent.com/11954798/99391258-10155500-292e-11eb-84cc-3173bf01617f.png)

**Comment by Sandeep-Malhotra** [comment]
I got this issue when trying to use db-deployer-java

![image](https://user-images.githubusercontent.com/11954798/99487197-e43fb100-29b9-11eb-83de-f3198c1bd377.png)

**Comment by gregorwolf** [comment]
Please set:

`export JAVA_HOME=/home/vcap/app/.java-buildpack/open_jdk_jre`

then copy the command and execute it directly. I guess you get the same error as I've documented in [SAP Cloud Platform Trial, PostgreSQL Hyperscaler Option](https://github.com/gregorwolf/pg-beershop/tree/master/db-deployer-java#sap-cloud-platform-trial-postgresql-hyperscaler-option). I've mentioned this in the SAP Community Q&A post [Can't connect to PostgreSQL on SAP CP Trial, Hyperscaler Option](https://answers.sap.com/questions/13182819/cant-connect-to-postgresql-on-sap-cp-trial-hypersc.html) where Manjunath Baburao [just replied with another tip](https://answers.sap.com/comments/13188807/view.html). Please reply also there if you make any progress.

**Comment by Sandeep-Malhotra** [comment]
Do you want me to set JAVA_HOME in CF vcap folder and re run the deployer.sh . 

I did and got the same error.

**Comment by gregorwolf** [comment]
Thanks to the update from @mikezaschka to [cds-dbm](https://github.com/mikezaschka/cds-dbm) the deployment now works. Check out the instructions at [Run on SAP Cloud Platform - Cloud Foundry Environment with Hyperscaler Option](https://github.com/gregorwolf/pg-beershop#run-on-sap-cloud-platform---cloud-foundry-environment-with-hyperscaler-option).

**Comment by gregorwolf** [comment]
Please comment whan you still have issues.

**Comment by Sandeep-Malhotra** [comment]
Thanks Gregor As you said I am able to deploy but I have to create tables manually using Adminer. I will try to deploy cds-dbm so that I needn't to create tables and views manually via SQL.
Really thanks for your assistance

**Comment by Sandeep-Malhotra** [comment]
I have few doubts
1  cds-dbm is used to deploy to cf or local or both. 
2 Do I need to db-deployer-apt to deploy to CF 

Thanks in advance

**Comment by gregorwolf** [comment]
cds-dbm is used for local deployment as well for the CF deployment. Yes, you need to use the db-deployer-apt. Please read through the updated section of the README: [Run on SAP Cloud Platform - Cloud Foundry Environment with Hyperscaler Option](https://github.com/gregorwolf/pg-beershop#run-on-sap-cloud-platform---cloud-foundry-environment-with-hyperscaler-option) and also check out what is behind this scripts in the package.json to understand it.

**Comment by Sandeep-Malhotra** [comment]
Alright Noted with thanks .
