### ISSUE TITLE
Error while using - db-deployer-apt

### ISSUE THREAD

**Issue by Sandeep-Malhotra** [gregorwolf/pg-beershop#4]
Hello Gregor,
I tried db-deployer-apt  got an error
![image](https://user-images.githubusercontent.com/11954798/100196394-e7541780-2f4c-11eb-8318-f24d27a779df.png)

Am not sure whether I am missing something or not 

Kindly advise.

Regards,
Sandeep

**Comment by gregorwolf** [comment]
I think this output is just shown as an error. But actually it's fine. Unfortunately there is an issue that the current cds-dbm version has. Please check https://github.com/mikezaschka/cds-dbm/issues/1#issuecomment-733563349
